### PR TITLE
new types of serial

### PR DESCRIPTION
**Pull request by herrboyer**
* g - Magazine
* h - Blog
* j - Journal
* r - Repository
* s - Newsletter
* t - Directory

### CODE REVIEW

**Review by j0ack — APPROVED** [review]

**Comment by dwpeg** [comment]
This is actually officially called ≈ “type of continuing resource” rather than the “type of serial” and it is important that this terminology be in line with MARC21 and UNIMARC.  Can this be updated? (Deanna White at the ISSN International Centre)

**Comment by dwpeg** [comment]
See the description for position 21 here: https://www.loc.gov/marc/bibliographic/bd008s.html

**Comment by herrboyer** [comment]
Hi @dwpeg 

It's a bit hard to rewrite history in git so the [commit message](https://github.com/CIEPS/json-schema-himarc/commit/4ca4bb49b8315f127b85f26cd0289cffe54b96e5) will stay the same, but we can (and I just did) rename this pull request.

I used "type of serial" because it was the _title_ of the changelog found at the bottom of the page you linked:

image

Sorry about this

**Comment by dwpeg** [comment]
> Hi @dwpeg
> 
> It's a bit hard to rewrite history in git so the [commit message](https://github.com/CIEPS/json-schema-himarc/commit/4ca4bb49b8315f127b85f26cd0289cffe54b96e5) will stay the same, but we can (and I just did) rename this pull request.
> 
> I used "type of serial" because it was the _title_ of the changelog found at the bottom of the page you linked:
> 
> image
> 
> And missed the fact that it was renamed... Sorry about this

No worries! Thanks for the prompt update :-)

**Pull request merged**
